// browser/ module — split from monolithic browser.rs (4512 lines)
// Each submodule handles a specific domain of browser commands.

mod agent_computer;
mod auth;
mod content;
mod cookies;
mod crawl;
mod dom;
mod emulation;
mod helpers;
mod interact;
mod media;
mod monitoring;
mod nav;
mod network;
mod shell;
mod spa_harness;
mod tabs;
mod web_storage;
mod workflow_cli;

// Re-export all public functions so callers can use commands::browser::function_name
pub use agent_computer::{
    agent_loop,
    goal_assert,
    annotated_observe,
    session_context,
    auto_chain,
    think,
    annotated_screenshot,
    adaptive_retry,
    click_at_coords,
    multi_page_sync,
    input_replay_file,
    page_state_cli,
    plan_exec_cli,
    page_info_cli,
    assert_checks_cli,
    element_detail_cli,
};
pub use auth::{
    passkey_enable,
    passkey_add,
    passkey_list,
    passkey_log,
    passkey_disable,
    passkey_remove,
    passkey_register,
    passkey_set_file,
    stealth_inject,
    stealth_tls_apply,
    stealth_webrtc_block,
    stealth_battery_spoof,
    stealth_sensor_block,
    stealth_canvas_advanced,
    stealth_timezone_sync,
    stealth_font_protect,
    stealth_behavior_sim,
    stealth_behavior_stop,
    stealth_rotate,
    stealth_detection_audit,
    antibot_inject,
    antibot_test,
    antibot_profiles,
    captcha_detect,
    captcha_wait,
    captcha_screenshot,
    captcha_inject,
    captcha_solve,
    captcha_types,
    stealth_check,
    passkey_vault_list,
    passkey_vault_save,
    passkey_vault_remove,
    passkey_vault_clear_site,
    passkey_vault_export,
    passkey_import_bitwarden,
    passkey_import_1password,
    passkey_import_cxf,
};
pub use content::{
    get,
    eval,
    set_content,
    extract_content,
    extract_metadata,
    stream_extract,
    structured_extract_all,
    structured_json_ld,
    structured_open_graph,
    structured_twitter_card,
    structured_metadata,
    structured_validate,
    find_action,
};
pub use cookies::{
    cookie_get,
    cookie_set,
    cookie_delete,
    cookie_clear,
    cookie_export,
    cookie_import,
    cookie_jar_export,
    cookie_jar_import,
    cookie_jar_clear,
};
pub use crawl::{
    proxy_create_pool,
    proxy_chrome_args,
    proxy_next,
    intercept_set,
    intercept_log,
    intercept_clear,
    bench_run,
    bench_report,
    geo_apply,
    geo_presets,
    geo_current,
    request_execute,
    request_batch,
    spider_crawl,
    spider_resume,
    spider_summary,
    robots_parse,
    robots_check,
    robots_sitemaps,
    graph_extract,
    graph_build,
    graph_analyze,
    graph_export,
    ratelimit_set,
    ratelimit_stats,
    ratelimit_reset,
    retry_enqueue,
    retry_next,
    retry_success,
    retry_fail,
    retry_stats,
    retry_clear,
    retry_save,
    retry_load,
    pipeline_run,
    pipeline_validate,
    pipeline_save_file,
    pipeline_load_file,
    proxy_health_check,
    proxy_health_check_all,
    proxy_health_rank,
    proxy_health_filter,
    schedule_add,
    schedule_remove,
    schedule_pause,
    schedule_resume,
    schedule_list,
    schedule_stats,
    schedule_save,
    schedule_load,
    pool_add,
    pool_next,
    pool_stats,
    pool_cleanup,
    pool_save,
    pool_load,
};
pub use dom::{
    adaptive_fingerprint,
    adaptive_relocate,
    adaptive_track,
    adaptive_relocate_all,
    adaptive_save,
    adaptive_load,
    dom_observe,
    dom_mutations,
    dom_stop,
    dom_snapshot,
    iframe_list,
    iframe_eval,
    iframe_content,
    select_css,
    select_xpath,
    select_text,
    select_regex,
    select_auto,
    nav_parent,
    nav_children,
    nav_next_sibling,
    nav_prev_sibling,
    nav_siblings,
    nav_similar,
    nav_above,
    nav_below,
};
pub use emulation::{
    emulate_viewport,
    emulate_device,
    emulate_user_agent,
    emulate_geolocation,
    emulate_color_scheme,
    emulate_clear,
    adv_emulation_orientation,
    adv_emulation_permission,
    adv_emulation_battery,
    adv_emulation_connection,
    adv_emulation_cpu_cores,
    adv_emulation_memory,
    adv_emulation_navigator_info,
    fingerprint_apply,
    fingerprint_detect,
    fingerprint_list,
};
// helpers used internally by submodules via super::helpers
pub use interact::{
    click,
    dblclick,
    type_text,
    fill,
    focus,
    hover,
    scroll_into_view,
    check,
    uncheck,
    select_option,
    tap,
    drag,
    upload,
    bounding_box,
    press_key,
    key_down,
    key_up,
    keyboard_shortcut,
    keyboard_type,
    keyboard_insert_text,
    scroll,
    is_check,
    mouse_move,
    mouse_down,
    mouse_up,
    mouse_wheel,
    highlight,
    page_errors,
    window_new,
    set_offline,
    set_extra_headers,
    set_credentials,
    route_add,
    route_remove,
    requests_list,
    close_page,
};
pub use media::{
    screenshot,
    pdf,
    print_pdf,
    print_metrics,
    screenshot_diff_compare,
    screenshot_diff_regression,
    snapshot_take,
    snapshot_compare,
    snapshot_watch,
    snapshot_agent,
    diff_snapshot,
    diff_screenshot,
    diff_url,
    auth_state_save,
    auth_state_load,
    auth_state_list,
    auth_state_show,
    auth_state_rename,
    auth_state_clear,
    auth_state_clean,
    stream_start,
    stream_stop,
    stream_frame,
    stream_capture,
    recording_start,
    recording_stop,
    recording_status,
    video_encode,
    video_record,
};
pub use monitoring::{
    coverage_js_start,
    coverage_js_stop,
    coverage_css_start,
    coverage_css_report,
    a11y_tree,
    a11y_element,
    a11y_audit,
    perf_trace_start,
    perf_trace_stop,
    perf_metrics,
    perf_timing,
    perf_resources,
    console_start,
    console_drain,
    console_clear,
    dialog_set_handler,
    dialog_history,
    dialog_clear,
    worker_list,
    worker_unregister,
    worker_info,
    page_watcher_start,
    page_watcher_drain,
    page_watcher_stop,
    page_watcher_state,
};
pub use nav::{
    navigate,
    back,
    forward,
    reload,
    wait_ms,
    wait_for_selector,
    wait_for_url,
    wait_for_text,
    wait_for_load,
    wait_for_function,
};
pub use network::{
    network_block,
    har_start,
    har_drain,
    har_export,
    ws_start,
    ws_drain,
    ws_export,
    ws_connections,
    throttle_set,
    throttle_custom,
    throttle_clear,
    network_log_start,
    network_log_drain,
    network_log_summary,
    network_log_stop,
    network_log_export,
    domain_block,
    domain_block_category,
    domain_unblock,
    domain_stats,
    domain_list,
    domain_categories,
    http_get,
    http_post,
    http_head,
    http_fetch,
    http_adaptive,
};
pub use shell::{shell_repl};
pub use tabs::{
    new_page,
    tab_list,
    tab_new,
    tab_close,
    tab_switch,
    tab_count_cmd,
    download_set_path,
    download_list,
    download_fetch,
    download_wait,
    download_clear,
};
pub use web_storage::{
    web_storage_local_get,
    web_storage_local_set,
    web_storage_local_clear,
    web_storage_session_get,
    web_storage_session_set,
    web_storage_session_clear,
    web_storage_indexeddb_list,
    web_storage_clear_all,
};
pub use spa_harness::{
    spa_nav_watch,
    framework_detect,
    virtual_scroll_detect,
    virtual_scroll_extract,
    wait_hydration,
    wait_animation,
    trigger_lazy_load,
    wait_network_idle,
    state_inspect,
    form_wizard_track,
    dynamic_import_wait,
    parallel_exec,
    health_check,
    circuit_breaker,
    reconnect_cdp,
    gc_tabs,
    watchdog,
};
pub use workflow_cli::{
    workflow_exec,
    workflow_validate_cli,
};
