/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * High-level browser automation powered by chromiumoxide (native CDP).
 *
 * ```js
 * const browser = await NativeBrowser.launch(true);
 * await browser.goto("https://example.com");
 * const title = await browser.getTitle();
 * const screenshot = await browser.screenshot();
 * await browser.close();
 * ```
 */
export declare class NativeBrowser {
  /** Launch a new browser instance. Returns a Promise. */
  static launch(headless?: boolean | undefined | null): Promise<NativeBrowser>
  /** Connect to an existing browser via CDP WebSocket URL. */
  static connect(wsUrl: string): Promise<NativeBrowser>
  /** Navigate to a URL. */
  goto(url: string): Promise<void>
  /** Get current page URL. */
  getUrl(): Promise<string>
  /** Get page title. */
  getTitle(): Promise<string>
  /** Get page HTML content. */
  content(): Promise<string>
  /** Set page HTML content. */
  setContent(html: string): Promise<void>
  /** Take a viewport screenshot (PNG). Returns raw bytes. */
  screenshot(): Promise<Buffer>
  /** Take a full-page screenshot (PNG). Returns raw bytes. */
  screenshotFull(): Promise<Buffer>
  /** Screenshot a specific element by CSS selector (PNG). */
  screenshotElement(selector: string): Promise<Buffer>
  /** Save page as PDF. Returns raw bytes. */
  pdf(): Promise<Buffer>
  /** Evaluate JavaScript in the page. Returns JSON string. */
  evaluate(expression: string): Promise<string>
  /** Click an element by CSS selector. */
  click(selector: string): Promise<void>
  /** Double-click an element by CSS selector. */
  doubleClick(selector: string): Promise<void>
  /** Type text into an element (key-by-key). */
  type(selector: string, text: string): Promise<void>
  /** Get text content of an element. */
  getText(selector: string): Promise<string>
  /** Get an attribute value from an element. */
  getAttribute(selector: string, attribute: string): Promise<string | null>
  /** Hover over an element. */
  hover(selector: string): Promise<void>
  /** Scroll an element into view. */
  scrollIntoView(selector: string): Promise<void>
  /** Check a checkbox. */
  check(selector: string): Promise<void>
  /** Uncheck a checkbox. */
  uncheck(selector: string): Promise<void>
  /** Select an option in a `<select>` element by value. */
  selectOption(selector: string, value: string): Promise<void>
  /** Wait for a selector to appear (timeout in ms). */
  waitForSelector(selector: string, timeoutMs?: number | undefined | null): Promise<void>
  /** Wait for URL to contain a pattern (timeout in ms). */
  waitForUrl(pattern: string, timeoutMs?: number | undefined | null): Promise<void>
  /** Go back in history. */
  goBack(): Promise<void>
  /** Go forward in history. */
  goForward(): Promise<void>
  /** Reload the page. */
  reload(): Promise<void>
  /** Inject stealth anti-detection patches. Returns the fingerprint used. */
  injectStealth(): Promise<FingerprintInfo>
  /** Open a new page/tab and switch to it. */
  newPage(url?: string | undefined | null): Promise<void>
  /** Enable network observation (intercept requests/responses). */
  observeNetwork(): Promise<void>
  /** Get intercepted requests (after `observeNetwork`). Returns JSON string. */
  getRequests(): Promise<string>
  /** Get intercepted responses (after `observeNetwork`). Returns JSON string. */
  getResponses(): Promise<string>
  /** Wait for a specified number of milliseconds. */
  wait(ms: number): Promise<void>
  /** Close the browser. */
  close(): Promise<void>
  /** Get all cookies (including httpOnly) via CDP. */
  getCookies(): Promise<string>
  /** Set a cookie. Accepts a JSON string of SetCookieParams. */
  setCookie(paramsJson: string): Promise<void>
  /** Delete cookies by name (optional domain/path). */
  deleteCookies(name: string, domain?: string | undefined | null, path?: string | undefined | null): Promise<void>
  /** Clear all browser cookies. */
  clearCookies(): Promise<void>
  /** Press a key (keyDown + keyUp). */
  pressKey(key: string): Promise<void>
  /** Send a keyboard shortcut (e.g., "Control+a", "Meta+c"). */
  keyboardShortcut(shortcut: string): Promise<void>
  /** Hold a key down. */
  keyDown(key: string): Promise<void>
  /** Release a key. */
  keyUp(key: string): Promise<void>
  /** Fill an input field (clear + set value + fire events). */
  fill(selector: string, value: string): Promise<void>
  /** Drag an element and drop onto another (CSS selectors). */
  dragAndDrop(source: string, target: string): Promise<void>
  /** Upload files to a `<input type="file">` element. */
  uploadFile(selector: string, filePaths: Array<string>): Promise<void>
  /** Get the bounding box of an element. Returns { x, y, width, height }. */
  boundingBox(selector: string): Promise<string>
  /** Tap an element (touch simulation). */
  tap(selector: string): Promise<void>
  /** Set viewport dimensions and device emulation. */
  setViewport(width: number, height: number, deviceScaleFactor?: number | undefined | null, isMobile?: boolean | undefined | null, hasTouch?: boolean | undefined | null): Promise<void>
  /** Set viewport from a device preset name (desktop, iphone14, ipad, pixel7). */
  setDevice(device: string): Promise<void>
  /** Clear viewport override (revert to browser defaults). */
  clearViewport(): Promise<void>
  /** Override the browser user agent string. */
  setUserAgent(userAgent: string): Promise<void>
  /** Set geolocation override. */
  setGeolocation(latitude: number, longitude: number, accuracy?: number | undefined | null): Promise<void>
  /** Emulate color scheme preference (dark/light). */
  setColorScheme(scheme: string): Promise<void>
  /** Block specific resource types (e.g., ["Image", "Font", "Stylesheet"]). */
  blockResources(resourceTypes: Array<string>): Promise<void>
  /**
   * Take a screenshot with custom options.
   * format: "png" | "jpeg" | "webp", quality: 0-100 (jpeg/webp only), fullPage: boolean
   */
  screenshotWithOptions(format?: string | undefined | null, quality?: number | undefined | null, fullPage?: boolean | undefined | null): Promise<Buffer>
  /** Generate PDF with custom options (landscape, scale, paper size). */
  pdfWithOptions(landscape?: boolean | undefined | null, scale?: number | undefined | null, paperWidth?: number | undefined | null, paperHeight?: number | undefined | null): Promise<Buffer>
  /** Start event observation (console + errors). Call drainEvents() to poll. */
  startEventStream(): Promise<void>
  /** Drain buffered events (console messages + page errors). Returns JSON array. */
  drainEvents(): Promise<string>
  /** Emit a custom event into the stream. */
  emitEvent(name: string, data: string): Promise<void>
  /** Start HAR (HTTP Archive) recording on the current page. */
  startHarRecording(): Promise<void>
  /** Drain new HAR entries from the page. Returns the number of new entries. */
  drainHarEntries(): Promise<number>
  /** Export all HAR entries as HAR 1.2 JSON string. */
  exportHar(): Promise<string>
  /** Start WebSocket frame interception on the current page. */
  startWsRecording(): Promise<void>
  /** Drain new WebSocket frames from the page. Returns the number of new frames. */
  drainWsFrames(): Promise<number>
  /** Export all captured WebSocket frames as JSON string. */
  exportWsFrames(): Promise<string>
  /** Get the count of active WebSocket connections. */
  activeWsConnections(): Promise<number>
  /** Start capturing console messages (log/warn/error/info/debug). */
  startConsoleCapture(): Promise<void>
  /** Drain captured console entries as JSON string. */
  drainConsoleEntries(): Promise<string>
  /** Clear the console capture buffer. */
  clearConsole(): Promise<void>
  /** Set dialog auto-handler (alert/confirm/prompt). */
  setDialogHandler(accept: boolean, promptText?: string | undefined | null): Promise<void>
  /** Get dialog history as JSON string. */
  getDialogHistory(): Promise<string>
  /** Clear dialog history. */
  clearDialogHistory(): Promise<void>
  /** Get all registered service workers as JSON string. */
  getServiceWorkers(): Promise<string>
  /** Unregister all service workers. Returns the number unregistered. */
  unregisterServiceWorkers(): Promise<number>
  /** Get worker info as JSON string. */
  getWorkerInfo(): Promise<string>
  /** Start observing DOM mutations (optional CSS selector target). */
  startDomObserver(selector?: string | undefined | null): Promise<void>
  /** Drain accumulated DOM mutations as JSON string. */
  drainDomMutations(): Promise<string>
  /** Stop the DOM observer. */
  stopDomObserver(): Promise<void>
  /** Get a snapshot of the current DOM as HTML string. */
  getDomSnapshot(selector?: string | undefined | null): Promise<string>
  /** List all iframes on the page as JSON string. */
  listIframes(): Promise<string>
  /** Execute JavaScript inside a specific iframe by index. Returns JSON string. */
  evalInIframe(index: number, expression: string): Promise<string>
  /** Get the inner HTML content of an iframe by index. */
  getIframeContent(index: number): Promise<string>
  /** Generate PDF with detailed options (JSON string of DetailedPdfOptions). Returns base64 PDF data. */
  printToPdf(options?: string | undefined | null): Promise<Buffer>
  /** Get page print preview metrics as JSON string. */
  getPrintMetrics(): Promise<string>
  /** Get all localStorage contents as JSON string. */
  getLocalStorage(): Promise<string>
  /** Set a localStorage item. */
  setLocalStorage(key: string, value: string): Promise<void>
  /** Clear all localStorage. */
  clearLocalStorage(): Promise<void>
  /** Get all sessionStorage contents as JSON string. */
  getSessionStorage(): Promise<string>
  /** Set a sessionStorage item. */
  setSessionStorage(key: string, value: string): Promise<void>
  /** Clear all sessionStorage. */
  clearSessionStorage(): Promise<void>
  /** Get IndexedDB database names as JSON string. */
  getIndexeddbDatabases(): Promise<string>
  /** Clear all site data (localStorage + sessionStorage + cookies + cache). */
  clearSiteData(): Promise<void>
  /** Start JavaScript code coverage collection via CDP Profiler. */
  startJsCoverage(): Promise<void>
  /** Stop JavaScript code coverage and return the report as JSON string. */
  stopJsCoverage(): Promise<string>
  /** Start CSS coverage collection. */
  startCssCoverage(): Promise<void>
  /** Get CSS coverage summary as JSON string. */
  getCssCoverage(): Promise<string>
  /** Get the full accessibility tree of the current page as JSON. */
  getAccessibilityTree(): Promise<string>
  /** Get accessibility info for a specific element by CSS selector. */
  getElementAccessibility(selector: string): Promise<string>
  /** Run an accessibility audit on the current page and return the report as JSON. */
  auditAccessibility(): Promise<string>
  /** Set network throttling to a named profile (fast3g, slow3g, offline, regular4g, wifi). */
  setNetworkThrottle(profile: string): Promise<void>
  /** Set custom network throttling conditions. */
  setNetworkThrottleCustom(downloadKbps: number, uploadKbps: number, latencyMs: number): Promise<void>
  /** Clear network throttling. */
  clearNetworkThrottle(): Promise<void>
  /** Start performance tracing on the current page. */
  startTracing(): Promise<void>
  /** Stop tracing and return the trace data as JSON. */
  stopTracing(): Promise<string>
  /** Get performance metrics from the current page as JSON. */
  getPerformanceMetrics(): Promise<string>
  /** Get navigation timing data as JSON. */
  getNavigationTiming(): Promise<string>
  /** Get resource timing entries as JSON. */
  getResourceTiming(): Promise<string>
  /** Create a proxy pool from JSON config. Returns the pool as JSON. */
  createProxyPool(config: string): string
  /** Get Chrome launch args for the first proxy in the pool. */
  getProxyChromeArgs(pool: string): Array<string>
  /** Rotate to the next proxy in the pool. Returns updated pool JSON. */
  nextProxy(pool: string): string
  /** Set request interception rules (JSON array of InterceptRule). */
  setInterceptRules(rules: string): Promise<void>
  /** Get intercepted request log as JSON. */
  getInterceptedRequests(): Promise<string>
  /** Clear all interception rules and restore originals. */
  clearInterceptRules(): Promise<void>
  /** Override device orientation sensor. */
  setDeviceOrientation(alpha: number, beta: number, gamma: number): Promise<void>
  /** Override a permission query result (e.g. "geolocation", "granted"). */
  overridePermission(permission: string, state: string): Promise<void>
  /** Override battery status API. */
  setBatteryStatus(level: number, charging: boolean): Promise<void>
  /** Override Network Information API. */
  setConnectionInfo(effectiveType: string, downlink: number, rtt: number): Promise<void>
  /** Override hardware concurrency (CPU cores). */
  setHardwareConcurrency(cores: number): Promise<void>
  /** Override device memory (GB). */
  setDeviceMemory(gb: number): Promise<void>
  /** Get current navigator properties as JSON. */
  getNavigatorInfo(): Promise<string>
  /** Run the CDP benchmark suite. Returns JSON string of BenchmarkSuite. */
  runBenchmark(iterations?: number | undefined | null): Promise<string>
  /** Apply a geo profile. Accepts a JSON string of GeoProfile. */
  applyGeoProfile(profile: string): Promise<void>
  /** List available geo preset names. */
  listGeoPresets(): Array<string>
  /** Get a geo preset by name. Returns JSON string of GeoProfile or null. */
  getGeoPreset(name: string): string | null
  /** Get current geolocation as seen by the page. Returns JSON string. */
  getCurrentGeo(): Promise<string>
  /** Export all cookies as a JSON CookieJar string. */
  exportCookies(): Promise<string>
  /** Import cookies from a JSON CookieJar string. Returns count imported. */
  importCookies(jar: string): Promise<number>
  /** Save cookies to a file. Returns count saved. */
  saveCookiesToFile(path: string): Promise<number>
  /** Load cookies from a file. Returns count loaded. */
  loadCookiesFromFile(path: string): Promise<number>
  /** Clear all cookies via cookie_jar module. */
  clearAllCookies(): Promise<void>
  /** Execute a single request with retry. Accepts JSON QueuedRequest. Returns JSON RequestResult. */
  executeRequest(request: string): Promise<string>
  /** Execute a batch of requests. Accepts JSON array of QueuedRequest + optional JSON QueueConfig. */
  executeBatch(requests: string, config?: string | undefined | null): Promise<string>
  /** Create a GET request. Returns JSON QueuedRequest. */
  createGetRequest(id: string, url: string): string
  /** Create a POST request. Returns JSON QueuedRequest. */
  createPostRequest(id: string, url: string, body: string): string
  /** CSS selector with pseudo-elements (::text, ::attr(name)). Returns JSON SelectorResult. */
  cssSelect(selector: string): Promise<string>
  /** XPath selector. Returns JSON SelectorResult. */
  xpathSelect(expression: string): Promise<string>
  /** Find elements by text content. Returns JSON SelectorResult. */
  findByText(text: string, tag?: string | undefined | null): Promise<string>
  /** Find elements by regex pattern. Returns JSON SelectorResult. */
  findByRegex(pattern: string, tag?: string | undefined | null): Promise<string>
  /** Auto-generate a unique CSS selector for an element. Returns the selector string. */
  autoSelector(targetSelector: string): Promise<string>
  /** Get parent element. Returns JSON NavElement or null. */
  getParent(selector: string): Promise<string | null>
  /** Get child elements. Returns JSON array of NavElement. */
  getChildren(selector: string): Promise<string>
  /** Get next sibling element. Returns JSON NavElement or null. */
  getNextSibling(selector: string): Promise<string | null>
  /** Get previous sibling element. Returns JSON NavElement or null. */
  getPrevSibling(selector: string): Promise<string | null>
  /** Get all sibling elements. Returns JSON array of NavElement. */
  getSiblings(selector: string): Promise<string>
  /** Find similar elements. Returns JSON array of NavElement. */
  findSimilar(selector: string): Promise<string>
  /** Get elements above the target. Returns JSON array of NavElement. */
  aboveElements(selector: string, limit?: number | undefined | null): Promise<string>
  /** Get elements below the target. Returns JSON array of NavElement. */
  belowElements(selector: string, limit?: number | undefined | null): Promise<string>
  /** Extract page content. Returns JSON ExtractResult. */
  extract(selector?: string | undefined | null, format?: string | undefined | null): Promise<string>
  /** Extract content and save to file. Returns bytes written. */
  extractToFile(outputPath: string, selector?: string | undefined | null): Promise<number>
  /** Get structured page metadata. Returns JSON object. */
  getPageMetadata(): Promise<string>
  /** Start network request/response logging. */
  startNetworkLog(): Promise<void>
  /** Drain captured network entries as JSON string. */
  drainNetworkLog(): Promise<string>
  /** Get network summary statistics as JSON string. */
  getNetworkSummary(): Promise<string>
  /** Stop network logging and restore originals. */
  stopNetworkLog(): Promise<void>
  /** Export network log to a JSON file. */
  exportNetworkLog(path: string): Promise<void>
  /** Start watching for page state changes. */
  startPageWatcher(): Promise<void>
  /** Drain accumulated page changes as JSON string. */
  drainPageChanges(): Promise<string>
  /** Stop the page watcher. */
  stopPageWatcher(): Promise<void>
  /** Get current page state snapshot as JSON string. */
  getPageState(): Promise<string>
  /** Run a crawl. Accepts SpiderConfig as JSON, returns Vec<CrawlResult> as JSON. */
  crawl(configJson: string): Promise<string>
  /** Compute crawl summary from results JSON. */
  crawlSummary(resultsJson: string): string
  /** Save crawl state to a JSON file. */
  saveCrawlState(stateJson: string, path: string): void
  /** Load crawl state from a JSON file. */
  loadCrawlState(path: string): string
  /** Export crawl results to file. Format: "json" (default) or "jsonl". */
  exportCrawlResults(resultsJson: string, path: string, format?: string | undefined | null): number
  /** Inject full stealth anti-bot patches. Returns JSON array of applied patch names. */
  injectStealthFull(): Promise<string>
  /** Run bot detection tests. Returns JSON object with scores. */
  botDetectionTest(): Promise<string>
  /** Get available stealth profiles. Returns JSON array. */
  stealthProfiles(): string
  /** Fingerprint a DOM element by CSS selector. Returns JSON. */
  fingerprintElement(selector: string): Promise<string>
  /** Relocate an element using a previously captured fingerprint (JSON). Returns JSON matches. */
  relocateElement(fingerprint: string): Promise<string>
  /** Track multiple elements by CSS selectors (JSON array). Optionally save to path. */
  trackElements(selectors: string, savePath?: string | undefined | null): Promise<string>
  /** Relocate all fingerprints (JSON array). Returns JSON array of (selector, matches). */
  relocateAll(fingerprints: string): Promise<string>
  /** Save fingerprints JSON to a file path. */
  saveFingerprints(fingerprints: string, path: string): void
  /** Load fingerprints from a file path. Returns JSON array. */
  loadFingerprints(path: string): string
  /** Block a list of domains (JSON array). Returns total blocked count. */
  blockDomains(domains: string): Promise<number>
  /** Block domains by category (ads, trackers, social, fonts, media). Returns total count. */
  blockCategory(category: string): Promise<number>
  /** Get blocking statistics as JSON. */
  blockStats(): Promise<string>
  /** Clear all blocked domains. */
  clearBlocks(): Promise<void>
  /** List currently blocked domains as JSON array. */
  listBlocked(): Promise<string>
  /** Get available block categories and their domain counts as JSON. */
  availableBlockCategories(): string
  /** Parse a shell command string. Returns JSON. */
  shellParse(input: string): string
  /** Get available shell commands. Returns JSON. */
  shellCommands(): string
  /** Save shell history (JSON) to file. */
  shellSaveHistory(history: string, path: string): void
  /** Load shell history from file. Returns JSON. */
  shellLoadHistory(path: string): string
}

/** Encrypted key-value store backed by sled + AES-256-GCM. */
export declare class NativeStore {
  /** Open (or create) an encrypted store at the given path. */
  constructor(path: string, password: string)
  /** Retrieve a value by key. */
  get(key: string): string | null
  /** Store a value. */
  set(key: string, value: string): void
  /** Delete a key, returns true if it existed. */
  delete(key: string): boolean
  /** List all keys in the store. */
  list(): Array<string>
  /** Check if a key exists. */
  contains(key: string): boolean
  /** Flush pending writes to disk. */
  flush(): void
}

/** AES-256-GCM decrypt. Input format: `salt(16) + nonce(12) + ciphertext`. */
export declare function decrypt(ciphertext: Buffer, password: string): Buffer

/** PBKDF2-HMAC-SHA256 key derivation (returns 32-byte key). */
export declare function deriveKey(password: string, salt: Buffer): Buffer

/** AES-256-GCM encrypt. Returns `salt(16) + nonce(12) + ciphertext`. */
export declare function encrypt(plaintext: Buffer, password: string): Buffer

/** Extract all links from HTML with external detection. */
export declare function extractLinks(html: string): Array<LinkInfo>

/** Extract all visible text from HTML. */
export declare function extractText(html: string): string

/** Stealth fingerprint configuration. */
export interface FingerprintInfo {
  platform: string
  hardwareConcurrency: number
  deviceMemory: number
}

/** Generate a PKCE S256 challenge pair. */
export declare function generatePkce(): PkceChallenge

/** Generate a 6-digit TOTP code (SHA-1, 30s period). */
export declare function generateTotp(secret: string): string

/** Link extracted from HTML. */
export interface LinkInfo {
  href: string
  text: string
  isExternal: boolean
}

/** Build and render an accessibility tree from HTML. */
export declare function parseAccessibilityTree(html: string): string

/** PKCE challenge pair (code_verifier + code_challenge). */
export interface PkceChallenge {
  verifier: string
  challenge: string
}

/** Query HTML with a CSS selector, returns JSON array of matching elements. */
export declare function querySelector(html: string, selector: string): string

/** Verify a TOTP code with ±1 step window. */
export declare function verifyTotp(secret: string, code: string): boolean
