/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * High-level browser automation powered by chromiumoxide (native CDP).
 *
 * ```js
 * const browser = await NativeBrowser.launch(true);
 * await browser.goto("https://example.com");
 * const title = await browser.getTitle();
 * const screenshot = await browser.screenshot();
 * await browser.close();
 * ```
 */
export declare class NativeBrowser {
  /** Launch a new browser instance. Returns a Promise. */
  static launch(headless?: boolean | undefined | null): Promise<NativeBrowser>
  /** Connect to an existing browser via CDP WebSocket URL. */
  static connect(wsUrl: string): Promise<NativeBrowser>
  /** Navigate to a URL. */
  goto(url: string): Promise<void>
  /** Get current page URL. */
  getUrl(): Promise<string>
  /** Get page title. */
  getTitle(): Promise<string>
  /** Get page HTML content. */
  content(): Promise<string>
  /** Set page HTML content. */
  setContent(html: string): Promise<void>
  /** Take a viewport screenshot (PNG). Returns raw bytes. */
  screenshot(): Promise<Buffer>
  /** Take a full-page screenshot (PNG). Returns raw bytes. */
  screenshotFull(): Promise<Buffer>
  /** Screenshot a specific element by CSS selector (PNG). */
  screenshotElement(selector: string): Promise<Buffer>
  /** Save page as PDF. Returns raw bytes. */
  pdf(): Promise<Buffer>
  /** Evaluate JavaScript in the page. Returns JSON string. */
  evaluate(expression: string): Promise<string>
  /** Click an element by CSS selector. */
  click(selector: string): Promise<void>
  /** Double-click an element by CSS selector. */
  doubleClick(selector: string): Promise<void>
  /** Type text into an element (key-by-key). */
  type(selector: string, text: string): Promise<void>
  /** Get text content of an element. */
  getText(selector: string): Promise<string>
  /** Get an attribute value from an element. */
  getAttribute(selector: string, attribute: string): Promise<string | null>
  /** Hover over an element. */
  hover(selector: string): Promise<void>
  /** Scroll an element into view. */
  scrollIntoView(selector: string): Promise<void>
  /** Check a checkbox. */
  check(selector: string): Promise<void>
  /** Uncheck a checkbox. */
  uncheck(selector: string): Promise<void>
  /** Select an option in a `<select>` element by value. */
  selectOption(selector: string, value: string): Promise<void>
  /** Wait for a selector to appear (timeout in ms). */
  waitForSelector(selector: string, timeoutMs?: number | undefined | null): Promise<void>
  /** Wait for URL to contain a pattern (timeout in ms). */
  waitForUrl(pattern: string, timeoutMs?: number | undefined | null): Promise<void>
  /** Go back in history. */
  goBack(): Promise<void>
  /** Go forward in history. */
  goForward(): Promise<void>
  /** Reload the page. */
  reload(): Promise<void>
  /** Inject stealth anti-detection patches. Returns the fingerprint used. */
  injectStealth(): Promise<FingerprintInfo>
  /** Open a new page/tab and switch to it. */
  newPage(url?: string | undefined | null): Promise<void>
  /** Enable network observation (intercept requests/responses). */
  observeNetwork(): Promise<void>
  /** Get intercepted requests (after `observeNetwork`). Returns JSON string. */
  getRequests(): Promise<string>
  /** Get intercepted responses (after `observeNetwork`). Returns JSON string. */
  getResponses(): Promise<string>
  /** Wait for a specified number of milliseconds. */
  wait(ms: number): Promise<void>
  /** Close the browser. */
  close(): Promise<void>
  /** Get all cookies (including httpOnly) via CDP. */
  getCookies(): Promise<string>
  /** Set a cookie. Accepts a JSON string of SetCookieParams. */
  setCookie(paramsJson: string): Promise<void>
  /** Delete cookies by name (optional domain/path). */
  deleteCookies(name: string, domain?: string | undefined | null, path?: string | undefined | null): Promise<void>
  /** Clear all browser cookies. */
  clearCookies(): Promise<void>
  /** Press a key (keyDown + keyUp). */
  pressKey(key: string): Promise<void>
  /** Send a keyboard shortcut (e.g., "Control+a", "Meta+c"). */
  keyboardShortcut(shortcut: string): Promise<void>
  /** Hold a key down. */
  keyDown(key: string): Promise<void>
  /** Release a key. */
  keyUp(key: string): Promise<void>
  /** Fill an input field (clear + set value + fire events). */
  fill(selector: string, value: string): Promise<void>
  /** Drag an element and drop onto another (CSS selectors). */
  dragAndDrop(source: string, target: string): Promise<void>
  /** Upload files to a `<input type="file">` element. */
  uploadFile(selector: string, filePaths: Array<string>): Promise<void>
  /** Get the bounding box of an element. Returns { x, y, width, height }. */
  boundingBox(selector: string): Promise<string>
  /** Tap an element (touch simulation). */
  tap(selector: string): Promise<void>
}

/** Encrypted key-value store backed by sled + AES-256-GCM. */
export declare class NativeStore {
  /** Open (or create) an encrypted store at the given path. */
  constructor(path: string, password: string)
  /** Retrieve a value by key. */
  get(key: string): string | null
  /** Store a value. */
  set(key: string, value: string): void
  /** Delete a key, returns true if it existed. */
  delete(key: string): boolean
  /** List all keys in the store. */
  list(): Array<string>
  /** Check if a key exists. */
  contains(key: string): boolean
  /** Flush pending writes to disk. */
  flush(): void
}

/** AES-256-GCM decrypt. Input format: `salt(16) + nonce(12) + ciphertext`. */
export declare function decrypt(ciphertext: Buffer, password: string): Buffer

/** PBKDF2-HMAC-SHA256 key derivation (returns 32-byte key). */
export declare function deriveKey(password: string, salt: Buffer): Buffer

/** AES-256-GCM encrypt. Returns `salt(16) + nonce(12) + ciphertext`. */
export declare function encrypt(plaintext: Buffer, password: string): Buffer

/** Extract all links from HTML with external detection. */
export declare function extractLinks(html: string): Array<LinkInfo>

/** Extract all visible text from HTML. */
export declare function extractText(html: string): string

/** Stealth fingerprint configuration. */
export interface FingerprintInfo {
  platform: string
  hardwareConcurrency: number
  deviceMemory: number
}

/** Generate a PKCE S256 challenge pair. */
export declare function generatePkce(): PkceChallenge

/** Generate a 6-digit TOTP code (SHA-1, 30s period). */
export declare function generateTotp(secret: string): string

/** Link extracted from HTML. */
export interface LinkInfo {
  href: string
  text: string
  isExternal: boolean
}

/** Build and render an accessibility tree from HTML. */
export declare function parseAccessibilityTree(html: string): string

/** PKCE challenge pair (code_verifier + code_challenge). */
export interface PkceChallenge {
  verifier: string
  challenge: string
}

/** Query HTML with a CSS selector, returns JSON array of matching elements. */
export declare function querySelector(html: string, selector: string): string

/** Verify a TOTP code with ±1 step window. */
export declare function verifyTotp(secret: string, code: string): boolean
