/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Encrypted key-value store backed by sled + AES-256-GCM. */
export declare class NativeStore {
  /** Open (or create) an encrypted store at the given path. */
  constructor(path: string, password: string)
  /** Retrieve a value by key. */
  get(key: string): string | null
  /** Store a value. */
  set(key: string, value: string): void
  /** Delete a key, returns true if it existed. */
  delete(key: string): boolean
  /** List all keys in the store. */
  list(): Array<string>
  /** Check if a key exists. */
  contains(key: string): boolean
  /** Flush pending writes to disk. */
  flush(): void
}

/** AES-256-GCM decrypt. Input format: `salt(16) + nonce(12) + ciphertext`. */
export declare function decrypt(ciphertext: Buffer, password: string): Buffer

/** PBKDF2-HMAC-SHA256 key derivation (returns 32-byte key). */
export declare function deriveKey(password: string, salt: Buffer): Buffer

/** AES-256-GCM encrypt. Returns `salt(16) + nonce(12) + ciphertext`. */
export declare function encrypt(plaintext: Buffer, password: string): Buffer

/** Extract all links from HTML with external detection. */
export declare function extractLinks(html: string): Array<LinkInfo>

/** Extract all visible text from HTML. */
export declare function extractText(html: string): string

/** Generate a PKCE S256 challenge pair. */
export declare function generatePkce(): PkceChallenge

/** Generate a 6-digit TOTP code (SHA-1, 30s period). */
export declare function generateTotp(secret: string): string

/** Link extracted from HTML. */
export interface LinkInfo {
  href: string
  text: string
  isExternal: boolean
}

/** Build and render an accessibility tree from HTML. */
export declare function parseAccessibilityTree(html: string): string

/** PKCE challenge pair (code_verifier + code_challenge). */
export interface PkceChallenge {
  verifier: string
  challenge: string
}

/** Query HTML with a CSS selector, returns JSON array of matching elements. */
export declare function querySelector(html: string, selector: string): string

/** Verify a TOTP code with ±1 step window. */
export declare function verifyTotp(secret: string, code: string): boolean
